.\" This man page was originally written by pema@niksula.hut.fi for XBill
.\" It's currently maintained by xylem2020@gmail.com
.TH "xlennart" "6" "March 2015" "Version 1.1.1"
.SH NAME
xlennart \- save your computers from SystenD [TM] virus
.SH SYNOPSIS
.sp
.B xlennart [-l\fI level\fP] [--gui \fIgui\fP] [--size\fIsize\fP] [-v] [-h]
.SH DESCRIPTION
.PP
Ever get the feeling that nothing is going right?  You're a sysadmin, and
someone's trying to destroy your computers.  The little people running
around the screen are trying to infect your computers with SystenD [TM],
a virus cleverly designed to resemble a popular init system.  Your
objective is to click the mouse on them, ending their potential threat.
If one of the people reaches a computer, it will attempt to replace your
operating system with the virus it carries. It will then attempt to run off
the screen with your vital software.  The game ends when only 1 (or 0) of
your computers are being productive.  Additionally, some computers are
connected with network cables.  When one computer on a network becomes 
infected, a spark will be sent down the cable, and will infect the computer
on the other end when it reaches there.
.PP
Clicking the button on one of the little people will cause it to cry out in
pain and melt (id software eat your heart out!), dropping the stolen os if it
is carrying one.  If a computer is running SystenD or is temporarily off, the
os can be dragged back to the computer (or another computer compatible with
that os).  To extinguish a spark, drag the bucket of water from the upper
left corner onto it.
.PP
The status bar at the bottom tells the following:
.br
        Number of Lenns on/off the screen
.br
        Number of Computers running their init/off/SystenD
.br
        Level
.br
        Score
.SH OPTIONS
.TP
.B \-l\fI n\fP
Start at level \fIn\fP.
.TP
.B \--gui\fI gui
Use a specific front end.  The possible values are \fIgtk\fP, \fImotif\fP,
and \fIathena\fP.  Note that some of these may not be compiled into the
binary.
.TP
.B \--size\fI size\fP
Play on a field of \fIsize\fP x \fIsize\fP, instead of the normal 400x400.
\fIsize\fP must be larger than 400.
.TP
.B \-v
Print version number and exit.
.TP
.B \-h
Print help and exit.
.PP
When using the GTK gui, all standard GTK options are supported.  When using
the Athena or Motif GUI, all standard X Intrinsics options are supported.
.SH AUTHORS
Main Programmer:
.br
	Brian Wellington <bwelling@xbill.org> for XBill 2.1.

	Gethyn ThomasQuail <xylem2020@gmail.com> for XLennart.
.br
Programming & graphics:
.br
	Matias Duarte <matias@hyperimage.com> for XBill 2.0.

	Gethyn ThomasQuail <xylem2020@gmail.com> for XLennart.

	Daniel Reurich <daniel@reurich.kiwi.nz> for XLennart 
 	graphical character rework.
.br
Additional Credits:
.br
	Daniel Reurich <daniel@reurich.kiwi.nz> for creating
	and maintaining Debian/Devuan packaging (1.1.1).

	Michael Shigorin <shigorin@gmail.com> for configure and
	makefile clean up. Along with the addition of the GTK2
	patch (1.1).

	Dmitrij D. Czarkoff <czarkoff@gmail.com> for small code 
	clean up (1.1) and OpenBSD modifications.

	Vitalie Ciubotaru <vitalie@ciubotaru.tk> for small code
	clean up (1.1.1).
.br

.SH COPYING
Copyright (c) 1994-2001 Psychosoft
Copyright (c) 2015 Gethyn ThomasQuail
.PP
It's FREE! If you want to express your undying gratitude to us for
bringing a small bit of meaning into your otherwise pointless
existence, you could always send us e-mail.
xlennart is distributed under the GNU General Public License.
.PP
Go play the game now!
